services:
  nats:
    image: nats:2.14
    command: ["-js"]
    ports:
      - "127.0.0.1:4222:4222"
      - "127.0.0.1:8222:8222"
  mongo:
    image: mongo:8.3
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_DATABASE: telemetry
